export const SEARCH = 'SEARCH'
export const BOOKDETAIL = 'BOOKDETAIL'
export const GETSOURCE = 'GETSOURCE'
export const GETCATALOG = 'GETCATALOG'
export const GETCONTENT = 'GETCONTENT'
export const SETHISTORY = 'SETHISTORY'
export const SETKEYWORD = 'SETKEYWORD'